### ISSUE TITLE
Delay between SNS and Earth Search API

### ISSUE THREAD

**Issue by julianblue** [cirrus-geo/cirrus-earth-search#30]
hi @matthewhanson ,

is there a known delay in the publishing of the Sentinel 2 COGS and STAC Endpoint update ? When requesting the latests data from the earth search api right after a new SNS topic, the API does not seem to have that item yet. 

Thanks in advance.

**Comment by matthewhanson** [comment]
@julianblue Sorry for the huge delay on responding here, not sure if we had ever talked about this, but yes there can be a delay.   When the SNS is published it is not actually in the API yet, because the API ingest queue is also subscribed to the same SNS topic.  It's typically very quick, unless we are doing a batch ingest of items and then items can accrue in the queue
