### ISSUE TITLE
Less data in November 2020

### ISSUE THREAD

**Issue by tebadi** [cirrus-geo/cirrus-earth-search#7]
There is less data in November 2020 compared to other months. See below for examples:

sentinel-cogs/sentinel-s2-l2a-cogs/36/M/WU/2020/11/
sentinel-cogs/sentinel-s2-l2a-cogs/32/N/PG/2020/11/

Please let us know what causes this.

**Comment by matthewhanson** [comment]
@tebadi I've taken a look here. Indeed it looks like Nov is roughly 75% of previous months, almost 100k scenes. It looks like the missing scenes come from mid-November.  

But I see only 9 failed scenes since the beginning of Nov to now, and less than 1500 invalid scenes due to missing data geometries. 

So this means that Cirrus never got the SNS message for the new scene in s3, or if it did get it then it was unable to start processing for some reason.

I'll kick off a job to grab the source inventory again and run scenes from November that have not been processed yet. As long as they are in the source bucket in eu-central-1 they'll be added.

**Comment by TaiWilkin** [comment]
This is fixed in v1.
